import React, {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

async function fetchData(context) {
  const res = await fetch('https://api.thecatapi.com/v1/images/search');
  const data = await res.json();

  if (!data) {
    return {
      notFound: true
    }
  }
  return {
    props: {data}
  }
}

export default function Home({ data }) {
  const [imageData, setImageData] = useState(data)

  console.log({imageData})

  return (
    <div className={styles.container}>
      <Head>
        <title>Cat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <h1>
          CAT?
        </h1>
        <button className={styles.tempButton} onClick={async () => setImageData(await (await fetchData()).props.data)}>
          Cat
        </button>
        <img src={imageData[0].url} className={styles.homePhoto} />

      </div>

      <footer className={styles.footer}>
        Because cats
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  return fetchData(context)
}